<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.camunda.consulting</groupId>
    <artifactId>connector-runtime-bundle-by-jens</artifactId>
    <version>0.0.1</version>
    <packaging>jar</packaging>
    <description>Connectors Runtime with Kafka Connector</description>

    <properties>
        <connectors.version>8.4.6</connectors.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.camunda.connector</groupId>
            <artifactId>spring-boot-starter-camunda-connectors</artifactId>
            <version>${connectors.version}</version>
        </dependency>
        <dependency>
            <groupId>io.camunda.connector</groupId>
            <artifactId>connector-kafka</artifactId>
            <version>${connectors.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                    <configuration>
                        <environmentVariables>
                            <CAMUNDA_IDENTITY_AUDIENCE>operate-api</CAMUNDA_IDENTITY_AUDIENCE>
                            <CAMUNDA_IDENTITY_CLIENT_ID>connectors</CAMUNDA_IDENTITY_CLIENT_ID>
                            <CAMUNDA_IDENTITY_CLIENT_SECRET>XALaRPl5qwTEItdwCMiPS62nVpKs7dL7</CAMUNDA_IDENTITY_CLIENT_SECRET>
                            <CAMUNDA_IDENTITY_ISSUER_BACKEND_URL>http://localhost:18080/auth/realms/camunda-platform</CAMUNDA_IDENTITY_ISSUER_BACKEND_URL>
                            <CAMUNDA_IDENTITY_TYPE>KEYCLOAK</CAMUNDA_IDENTITY_TYPE>
                            <CAMUNDA_OPERATE_CLIENT_URL>http://localhost:8081</CAMUNDA_OPERATE_CLIENT_URL>
                            <CONNECTOR_KAFKA_EXECUTABLE>io.camunda.connector.kafka.inbound.KafkaExecutable</CONNECTOR_KAFKA_EXECUTABLE>
                            <KAFKA_BOOTSTRAP_SERVER>kafka:9093</KAFKA_BOOTSTRAP_SERVER>
                            <KAFKA_GROUP_ID>jensgroup</KAFKA_GROUP_ID>
                            <KAFKA_TOPIC>jenstest</KAFKA_TOPIC>
                            <SSL_TRUSTSTORE_LOCATION>/Users/jens/projects/git/j-lindner/kafka-inbound-via-code/docker/kafka-ssl/kafka.server.truststore.jks</SSL_TRUSTSTORE_LOCATION>
                            <SSL_TRUSTSTORE_PASSWORD>password</SSL_TRUSTSTORE_PASSWORD>
                            <ZEEBE_AUTHENTICATION_MODE>none</ZEEBE_AUTHENTICATION_MODE>
                            <ZEEBE_AUTHORIZATION_SERVER_URL>http://localhost:18080/auth/realms/camunda-platform/protocol/openid-connect/token</ZEEBE_AUTHORIZATION_SERVER_URL>
                            <ZEEBE_CLIENT_BROKER_GATEWAY_ADDRESS>localhost:26500</ZEEBE_CLIENT_BROKER_GATEWAY_ADDRESS>
                            <ZEEBE_CLIENT_CONFIG_PATH>/tmp/zeebe_auth_cache</ZEEBE_CLIENT_CONFIG_PATH>
                            <ZEEBE_CLIENT_ID>zeebe</ZEEBE_CLIENT_ID>
                            <ZEEBE_CLIENT_SECRET>zecret</ZEEBE_CLIENT_SECRET>
                            <ZEEBE_CLIENT_SECURITY_PLAINTEXT>true</ZEEBE_CLIENT_SECURITY_PLAINTEXT>
                            <ZEEBE_TOKEN_AUDIENCE>zeebe-api</ZEEBE_TOKEN_AUDIENCE>
                        </environmentVariables>
                    </configuration>
                </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <configuration>
                    <mainClass>com.camunda.consulting.kafkainboundviacode.KafkaInboundViaCodeApplication</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
